import type { Metadata } from "next";
import { Mouse_Memoirs} from "next/font/google";
import "./globals.css";

const inter = Mouse_Memoirs({subsets:["latin"], weight:['400']});

export const metadata: Metadata = {
  title: "Hangman Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
